/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SvAmbulanceWlList {
    }
}
declare global {
    interface HTMLSvAmbulanceWlListElement extends Components.SvAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLSvAmbulanceWlListElement: {
        prototype: HTMLSvAmbulanceWlListElement;
        new (): HTMLSvAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "sv-ambulance-wl-list": HTMLSvAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface SvAmbulanceWlList {
    }
    interface IntrinsicElements {
        "sv-ambulance-wl-list": SvAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sv-ambulance-wl-list": LocalJSX.SvAmbulanceWlList & JSXBase.HTMLAttributes<HTMLSvAmbulanceWlListElement>;
        }
    }
}
